#!/usr/bin/env bash

# get filepath of this script's parent directory (relative to pwd)
PARENT_DIR=$(dirname ${BASH_SOURCE})

if [ $# -ne 1 ]; then
    >&2 echo "Usage: $0 <.c file to compile>"
else
    clang-12 -emit-llvm $1 -c -o  ${1%.*}.bc
fi