#!/usr/bin/env bash

# get directory name relative to pwd
PARENT_DIR=$(dirname ${BASH_SOURCE})
cd "$PARENT_DIR/../tests/"

if [ $# -ne 1 ]; then
    >&2 echo "Usage: $0 <.c or .cpp file to compile>"
else
    clang++-12 -emit-llvm $1 -c -o  ${1%.*}.bc
fi