#!/usr/bin/env bash

# get filepath of this script's parent directory (relative to pwd)
PARENT_DIR=$(dirname ${BASH_SOURCE})
# cd "$PARENT_DIR/../tests/"

script_opt_usage() {
    >&2 echo "Usage: $0 (-h) <.bc file to compile>"
}

if [ $# -lt 1 ]; then
    script_opt_usage
    exit 1
fi

if [ $1 == "-h" ]; then
    opt-12  -load "${PARENT_DIR}/../build/utils/libutils_lib.so" \
        -load "${PARENT_DIR}/../build/boguscf-pass/BOGUS-CF.so" \
        -load "${PARENT_DIR}/../build/dopseq-pass/DOPSEQ.so" \
        --help
else
    script_opt_usage
    exit 1
fi

opt-12  -load "${PARENT_DIR}/../build/utils/libutils_lib.so" \
        -load "${PARENT_DIR}/../build/boguscf-pass/BOGUS-CF.so" \
        -load "${PARENT_DIR}/../build/dopseq-pass/DOPSEQ.so" \
        -"$2" < $1 > ${1%.*}.opt.bc